In [1]:
import pandas as pd

In [2]:
orf_df = pd.read_csv('output/orf.csv.gz', dtype=str)
orf_df["Metadata_NCBI_Gene_ID"] = orf_df["Metadata_NCBI_Gene_ID"].astype(str)

orf_df.head()

,Metadata_JCP2022,Metadata_broad_sample,Metadata_Name,Metadata_Vector,Metadata_Transcript,Metadata_Symbol,Metadata_NCBI_Gene_ID,Metadata_Taxon_ID,Metadata_Gene_Description,Metadata_Prot_Match,Metadata_Insert_Length,Metadata_pert_type,Metadata_Approved_Symbol
0,JCP2022_900001,BAD CONSTRUCT,BAD CONSTRUCT,pLX_304,NaN,NaN,nan,NaN,NaN,NaN,NaN,trt,NaN
1,JCP2022_900002,ccsbBroad304_00001,ORF008415.1_TRC304.1,pLX_304,NM_001160173.3,NAT1,9,9606,N-acetyltransferase 1,100.0,870.0,trt,NAT1
2,JCP2022_900003,ccsbBroad304_00002,ORF005388.1_TRC304.1,pLX_304,NM_001088.3,AANAT,15,9606,aralkylamine N-acetyltransferase,100.0,621.0,trt,AANAT
3,JCP2022_900004,ccsbBroad304_00003,ORF003876.1_TRC304.1,pLX_304,NM_000663.4,ABAT,18,9606,4-aminobutyrate aminotransferase,100.0,1500.0,trt,ABAT
4,JCP2022_900005,ccsbBroad304_00007,ORF004679.1_TRC304.1,pLX_304,NM_000018.4,ACADVL,37,9606,acyl-CoA dehydrogenase very long chain,100.0,1965.0,trt,ACADVL

In [3]:
crispr_df = pd.read_csv('output/crispr.csv.gz', dtype=str)
crispr_df["Metadata_NCBI_Gene_ID"] = crispr_df["Metadata_NCBI_Gene_ID"].astype(str)
crispr_df.head()

,Metadata_JCP2022,Metadata_NCBI_Gene_ID,Metadata_Symbol,Metadata_Approved_Symbol
0,JCP2022_800001,nan,no-guide,NaN
1,JCP2022_800002,nan,non-targeting,NaN
2,JCP2022_800003,2,A2M,A2M
3,JCP2022_800004,127550,A3GALT2,A3GALT2
4,JCP2022_800005,53947,A4GALT,A4GALT

### Read metadata files

In [4]:
corum_df = pd.read_csv("output/CORUM_proteincomplex_annotations.tsv", sep="\t").rename(
    columns={
        "Symbol": "Metadata_Approved_Symbol",
        "ComplexName": "Metadata_complexname",
    }
)
corum_df.head()

  Metadata_Approved_Symbol                               Metadata_complexname
0                      A2M                                   A2M-BCHE complex
1                     AAAS                               Nuclear pore complex
2                     AATF                            AATF-NGDN-NOL10 complex
3                    ABCB1  ABCB1-ANXA2-RACK1-SRC complex|ABCB1-PPP2R3C-TF...
4                   ABCB11                               ABCB11-CHMP5 complex

In [5]:
class_df = pd.read_csv(
    "output/human_protein_atlas_class_annotations.tsv.gz", sep="\t"
).rename(
    columns={
        "Gene": "Metadata_Approved_Symbol",
        "protein_class": "Metadata_protein_class",
    }
)
class_df.head()

  Metadata_Approved_Symbol                             Metadata_protein_class
0                     A1BG  Plasma proteins|Predicted intracellular protei...
1                     A1CF                   Predicted intracellular proteins
2                      A2M  Cancer-related genes|Candidate cardiovascular ...
3                    A2ML1  Disease related genes|Predicted intracellular ...
4                  A3GALT2                Enzymes|Predicted membrane proteins

In [6]:
disease_df = pd.read_csv(
    "output/human_protein_atlas_disease_annotations.tsv.gz", sep="\t"
).rename(
    columns={
        "Gene": "Metadata_Approved_Symbol",
        "disease_involvement": "Metadata_disease_involvement",
    }
)
disease_df.head()

  Metadata_Approved_Symbol                       Metadata_disease_involvement
0                      A2M                               Cancer-related genes
1                     AAAS                                    Disease variant
2                    AAGAB                           Palmoplantar keratoderma
3                    AANAT                                    Disease variant
4                    AARS1  Charcot-Marie-Tooth disease|Disease variant|Ep...

In [7]:
location_df = pd.read_csv(
    "output/human_protein_atlas_location_annotations.tsv.gz",
    sep="\t",
    usecols=["Gene", "subcellular_location"],
).rename(
    columns={
        "Gene": "Metadata_Approved_Symbol",
        "subcellular_location": "Metadata_subcellular_location",
    }
)
location_df.head()

  Metadata_Approved_Symbol Metadata_subcellular_location
0                     A1CF                   Nucleoplasm
1                   A4GALT                  Mitochondria
2                     AAAS              Nuclear membrane
3                     AACS                      Vesicles
4                    AADAT               Plasma membrane

In [8]:
gene_family = pd.read_csv(
    "output/hgnc_approved_symbol_processed.tsv",
    sep="\t",
    usecols=["Approved_symbol", "Gene_group_ID"],
).rename(
    columns={
        "Approved_symbol": "Metadata_Approved_Symbol",
        "Gene_group_ID": "Metadata_gene_group_id",
    }
)
gene_family.head()

  Metadata_Approved_Symbol Metadata_gene_group_id
0                    A12M1                    NaN
1                    A12M2                    NaN
2                    A12M3                    NaN
3                    A12M4                    NaN
4                     A1BG                    594

In [9]:
homolog_df = pd.read_csv("output/homologues.tsv", sep="\t").rename(
    columns={"Symbol": "Metadata_Approved_Symbol", "Homologue": "Metadata_homologue"}
)

homolog_df.head()

  Metadata_Approved_Symbol  Metadata_homologue
0                     A1BG                True
1                     A1CF                True
2                      A2M                True
3                    A2ML1                True
4                  A3GALT2                True

In [10]:
go_df = pd.read_csv(
    "output/gene-ontology-annotations.tsv.gz", sep="\t"
).rename(
    columns={
        "gene": "Metadata_Approved_Symbol",
        "go_bp_list": "Metadata_biological_process",
        "go_cc_list": "Metadata_cellular_component",
        "go_mf_list": "Metadata_molecular_function",
    }
)
go_df.head()

,Metadata_Approved_Symbol,Metadata_biological_process,Metadata_cellular_component,Metadata_molecular_function
0,A1CF,GOBP_BASE_CONVERSION_OR_SUBSTITUTION_EDITING|G...,GOCC_APOLIPOPROTEIN_B_MRNA_EDITING_ENZYME_COMP...,GOMF_DOUBLE_STRANDED_RNA_BINDING|GOMF_MRNA_BIN...
1,A2M,GOBP_ACTIVATION_OF_IMMUNE_RESPONSE|GOBP_ACUTE_...,GOCC_BLOOD_MICROPARTICLE|GOCC_COLLAGEN_CONTAIN...,GOMF_CALCIUM_DEPENDENT_PROTEIN_BINDING|GOMF_CH...
2,A2ML1,GOBP_NEGATIVE_REGULATION_OF_CATALYTIC_ACTIVITY...,NaN,GOMF_ENDOPEPTIDASE_REGULATOR_ACTIVITY|GOMF_ENZ...
3,A3GALT2,GOBP_CARBOHYDRATE_DERIVATIVE_BIOSYNTHETIC_PROC...,GOCC_GOLGI_APPARATUS|GOCC_GOLGI_APPARATUS_SUBC...,GOMF_GALACTOSYLTRANSFERASE_ACTIVITY|GOMF_GLYCO...
4,A4GALT,GOBP_CARBOHYDRATE_DERIVATIVE_BIOSYNTHETIC_PROC...,GOCC_GOLGI_APPARATUS|GOCC_GOLGI_MEMBRANE,GOMF_ACETYLGLUCOSAMINYLTRANSFERASE_ACTIVITY|GO...

In [11]:
wp_df = pd.read_csv("output/wikipathway-annotations.tsv.gz", sep="\t").rename(
    columns={
        "gene": "Metadata_Approved_Symbol",
        "wikipathway": "Metadata_wikipathway",
    }
)
wp_df.head()

  Metadata_Approved_Symbol                               Metadata_wikipathway
0                  A3GALT2  WP_GANGLIO_SPHINGOLIPID_METABOLISM|WP_GLYCOSPH...
1                   A4GALT  WP_GLYCOSPHINGOLIPID_METABOLISM|WP_SYNTHESIS_O...
2                     AAAS              WP_PRADER_WILLI_AND_ANGELMAN_SYNDROME
3                    AADAT  WP_IDO_METABOLIC_PATHWAY|WP_KYNURENINE_PATHWAY...
4                     AAMP  WP_NUCLEOTIDE_BINDING_OLIGOMERIZATION_DOMAIN_N...

In [12]:
dependency_df = pd.read_csv(
    "output/CRISPRGeneDependency_U2OS.csv.gz", usecols=["geneID", "probability"]
).rename(
    columns={
        "geneID": "Metadata_NCBI_Gene_ID",
        "probability": "Metadata_dependency_probability",
    }
)

dependency_df.Metadata_NCBI_Gene_ID = dependency_df.Metadata_NCBI_Gene_ID.astype(str)
dependency_df.head()

  Metadata_NCBI_Gene_ID  Metadata_dependency_probability
0                     1                         0.025671
1                 29974                         0.006055
2                     2                         0.014716
3                144568                         0.042013
4                127550                         0.040916

In [13]:
expression_df = pd.read_csv(
    "output/OmicsExpressionProteinCodingGenesTPMLogp1_U2OS.csv.gz",
    usecols=["geneID", "TPM"],
).rename(columns={"geneID": "Metadata_NCBI_Gene_ID", "TPM": "Metadata_TPM"})

expression_df.Metadata_NCBI_Gene_ID = expression_df.Metadata_NCBI_Gene_ID.astype(str)
expression_df.head()

  Metadata_NCBI_Gene_ID  Metadata_TPM
0                  7105      4.519164
1                 64102      0.000000
2                  8813      6.673698
3                 57147      2.134221
4                 55732      4.107688

In [14]:
gene_effect_df = pd.read_csv(
    "output/CRISPRGeneEffect_U2OS.csv.gz", usecols=["geneID", "effect"]
).rename(columns={"geneID": "Metadata_NCBI_Gene_ID", "effect": "Metadata_gene_effect"})

gene_effect_df.Metadata_NCBI_Gene_ID = gene_effect_df.Metadata_NCBI_Gene_ID.astype(str)
gene_effect_df.head()

  Metadata_NCBI_Gene_ID  Metadata_gene_effect
0                     1             -0.129731
1                 29974              0.283889
2                     2              0.004612
3                144568             -0.070108
4                127550             -0.114891

In [15]:
orf_df = (
    orf_df.merge(corum_df, how="left", on="Metadata_Approved_Symbol")
    .merge(class_df, how="left", on="Metadata_Approved_Symbol")
    .merge(disease_df, how="left", on="Metadata_Approved_Symbol")
    .merge(location_df, how="left", on="Metadata_Approved_Symbol")
    .merge(gene_family, how="left", on="Metadata_Approved_Symbol")
    .merge(homolog_df, how="left", on="Metadata_Approved_Symbol")
    .merge(go_df, how="left", on="Metadata_Approved_Symbol")
    .merge(wp_df, how="left", on="Metadata_Approved_Symbol")
    .merge(dependency_df, how="left", on="Metadata_NCBI_Gene_ID")
    .merge(expression_df, how="left", on="Metadata_NCBI_Gene_ID")
    .merge(gene_effect_df, how='left', on="Metadata_NCBI_Gene_ID")
)

orf_df.count()

Metadata_JCP2022                   15142
Metadata_broad_sample              15142
Metadata_Name                      15132
Metadata_Vector                    15142
Metadata_Transcript                15106
Metadata_Symbol                    15107
Metadata_NCBI_Gene_ID              15142
Metadata_Taxon_ID                  15107
Metadata_Gene_Description          14853
Metadata_Prot_Match                14320
Metadata_Insert_Length             15141
Metadata_pert_type                 15142
Metadata_Approved_Symbol           14923
Metadata_complexname                3790
Metadata_protein_class             14484
Metadata_disease_involvement        4683
Metadata_subcellular_location      10363
Metadata_gene_group_id             11305
Metadata_homologue                 13482
Metadata_biological_process        12777
Metadata_cellular_component        10464
Metadata_molecular_function        11805
Metadata_wikipathway                6630
Metadata_dependency_probability    13922
Metadata_TPM                       14491
Metadata_gene_effect               13808
dtype: int64

In [16]:
crispr_df = (
    crispr_df.merge(corum_df, how="left", on="Metadata_Approved_Symbol")
    .merge(class_df, how="left", on="Metadata_Approved_Symbol")
    .merge(disease_df, how="left", on="Metadata_Approved_Symbol")
    .merge(location_df, how="left", on="Metadata_Approved_Symbol")
    .merge(gene_family, how="left", on="Metadata_Approved_Symbol")
    .merge(homolog_df, how="left", on="Metadata_Approved_Symbol")
    .merge(go_df, how="left", on="Metadata_Approved_Symbol")
    .merge(wp_df, how="left", on="Metadata_Approved_Symbol")
    .merge(dependency_df, how="left", on="Metadata_NCBI_Gene_ID")
    .merge(expression_df, how="left", on="Metadata_NCBI_Gene_ID")
    .merge(gene_effect_df, how='left', on="Metadata_NCBI_Gene_ID")
)

crispr_df.count()

Metadata_JCP2022                   7977
Metadata_NCBI_Gene_ID              7977
Metadata_Symbol                    7977
Metadata_Approved_Symbol           7975
Metadata_complexname               2242
Metadata_protein_class             7955
Metadata_disease_involvement       3470
Metadata_subcellular_location      5712
Metadata_gene_group_id             6857
Metadata_homologue                 7704
Metadata_biological_process        7674
Metadata_cellular_component        6239
Metadata_molecular_function        7648
Metadata_wikipathway               4784
Metadata_dependency_probability    7778
Metadata_TPM                       7956
Metadata_gene_effect               7776
dtype: int64

In [17]:
orf_df.to_csv('output/orf_metadata.tsv.gz', sep='\t', index=False)
crispr_df.to_csv('output/crispr_metadata.tsv.gz', sep='\t', index=False)