In [50]:
import pandas as pd

In [51]:
orf_df = pd.read_csv('output/orf.csv.gz')
orf_df.head()

,Metadata_JCP2022,Metadata_broad_sample,Metadata_Name,Metadata_Vector,Metadata_Transcript,Metadata_Symbol,Metadata_NCBI_Gene_ID,Metadata_Taxon_ID,Metadata_Gene_Description,Metadata_Prot_Match,Metadata_Insert_Length,Metadata_pert_type,Metadata_Approved_Symbol
0,JCP2022_900001,BAD CONSTRUCT,BAD CONSTRUCT,pLX_304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trt,NaN
1,JCP2022_900002,ccsbBroad304_00001,ORF008415.1_TRC304.1,pLX_304,NM_001160173.3,NAT1,9,9606,N-acetyltransferase 1,100.0,870.0,trt,NAT1
2,JCP2022_900003,ccsbBroad304_00002,ORF005388.1_TRC304.1,pLX_304,NM_001088.3,AANAT,15,9606,aralkylamine N-acetyltransferase,100.0,621.0,trt,AANAT
3,JCP2022_900004,ccsbBroad304_00003,ORF003876.1_TRC304.1,pLX_304,NM_000663.4,ABAT,18,9606,4-aminobutyrate aminotransferase,100.0,1500.0,trt,ABAT
4,JCP2022_900005,ccsbBroad304_00007,ORF004679.1_TRC304.1,pLX_304,NM_000018.4,ACADVL,37,9606,acyl-CoA dehydrogenase very long chain,100.0,1965.0,trt,ACADVL

In [52]:
crispr_df = pd.read_csv('output/crispr.csv.gz')
crispr_df.head()

,Metadata_JCP2022,Metadata_NCBI_Gene_ID,Metadata_Symbol,Metadata_Approved_Symbol
0,JCP2022_800001,NaN,no-guide,NaN
1,JCP2022_800002,NaN,non-targeting,NaN
2,JCP2022_800003,2.0,A2M,A2M
3,JCP2022_800004,127550.0,A3GALT2,A3GALT2
4,JCP2022_800005,53947.0,A4GALT,A4GALT

### Read metadata files

In [53]:
corum_df = pd.read_csv("output/CORUM_proteincomplex_annotations.tsv", sep="\t").rename(
    columns={
        "Symbol": "Metadata_Approved_Symbol",
        "ComplexName": "Metadata_complexname",
    }
)
corum_df.head()

  Metadata_Approved_Symbol                               Metadata_complexname
0                      A2M                                   A2M-BCHE complex
1                     AAAS                               Nuclear pore complex
2                     AATF                            AATF-NGDN-NOL10 complex
3                    ABCB1  ABCB1-ANXA2-RACK1-SRC complex|ABCB1-PPP2R3C-TF...
4                   ABCB11                               ABCB11-CHMP5 complex

In [54]:
class_df = pd.read_csv(
    "output/human_protein_atlas_class_annotations.tsv.gz", sep="\t"
).rename(
    columns={
        "Gene": "Metadata_Approved_Symbol",
        "protein_class": "Metadata_protein_class",
    }
)
class_df.head()

  Metadata_Approved_Symbol                             Metadata_protein_class
0                   TSPAN6  Predicted intracellular proteins|Predicted mem...
1                     TNMD                        Predicted membrane proteins
2                     DPM1  Disease related genes|Enzymes|Human disease re...
3                    SCYL3           Enzymes|Predicted intracellular proteins
4                 C1orf112                   Predicted intracellular proteins

In [55]:
disease_df = pd.read_csv(
    "output/human_protein_atlas_disease_annotations.tsv.gz", sep="\t"
).rename(
    columns={
        "Gene": "Metadata_Approved_Symbol",
        "disease_involvement": "Metadata_disease_involvement",
    }
)
disease_df.head()

  Metadata_Approved_Symbol                       Metadata_disease_involvement
0                     DPM1  Congenital disorder of glycosylation|Congenita...
1                      FGR                                     Proto-oncogene
2                      CFH  Age-related macular degeneration|Cancer-relate...
3                     GCLC        Disease variant|Hereditary hemolytic anemia
4                    LAS1L    Disease variant|Intellectual disability|Obesity

In [56]:
location_df = pd.read_csv(
    "output/human_protein_atlas_location_annotations.tsv.gz",
    sep="\t",
    usecols=["Gene", "subcellular_location"],
).rename(
    columns={
        "Gene": "Metadata_Approved_Symbol",
        "subcellular_location": "Metadata_subcellular_location",
    }
)
location_df.head()

  Metadata_Approved_Symbol Metadata_subcellular_location
0                   TSPAN6        Cell Junctions|Cytosol
1                    SCYL3       Golgi apparatus|Cytosol
2                 C1orf112                  Mitochondria
3                      FGR               Plasma membrane
4                      CFH                      Vesicles

In [57]:
gene_family = pd.read_csv(
    "output/hgnc_approved_symbol_processed.tsv",
    sep="\t",
    usecols=["Approved_symbol", "Gene_group_ID"],
).rename(
    columns={
        "Approved_symbol": "Metadata_Approved_Symbol",
        "Gene_group_ID": "Metadata_gene_group_id",
    }
)
gene_family.head()

  Metadata_Approved_Symbol Metadata_gene_group_id
0                     A1BG                    594
1                 A1BG-AS1                   1987
2                     A1CF                    725
3                    A1S9T                    NaN
4                      A2M                   2148

In [58]:
homolog_df = pd.read_csv("output/homologues.tsv", sep="\t").rename(
    columns={"Symbol": "Metadata_Approved_Symbol", "Homologue": "Metadata_homologue"}
)

homolog_df.head()

  Metadata_Approved_Symbol  Metadata_homologue
0                     A1BG                True
1                     A1CF                True
2                      A2M                True
3                    A2ML1                True
4                  A3GALT2                True

In [59]:
go_df = pd.read_csv(
    "output/gene-ontology-annotations.tsv.gz", sep="\t"
).rename(
    columns={
        "gene": "Metadata_Approved_Symbol",
        "go_bp_list": "Metadata_biological_process",
        "go_cc_list": "Metadata_cellular_component",
        "go_mf_list": "Metadata_molecular_function",
    }
)
go_df.head()

,Metadata_Approved_Symbol,Metadata_biological_process,Metadata_cellular_component,Metadata_molecular_function
0,A1CF,GOBP_BASE_CONVERSION_OR_SUBSTITUTION_EDITING|G...,GOCC_APOLIPOPROTEIN_B_MRNA_EDITING_ENZYME_COMP...,GOMF_DOUBLE_STRANDED_RNA_BINDING|GOMF_MRNA_BIN...
1,A2M,GOBP_ACTIVATION_OF_IMMUNE_RESPONSE|GOBP_ACUTE_...,GOCC_BLOOD_MICROPARTICLE|GOCC_COLLAGEN_CONTAIN...,GOMF_CALCIUM_DEPENDENT_PROTEIN_BINDING|GOMF_CH...
2,A2ML1,GOBP_NEGATIVE_REGULATION_OF_CATALYTIC_ACTIVITY...,NaN,GOMF_ENDOPEPTIDASE_REGULATOR_ACTIVITY|GOMF_ENZ...
3,A3GALT2,GOBP_CARBOHYDRATE_DERIVATIVE_BIOSYNTHETIC_PROC...,GOCC_GOLGI_APPARATUS|GOCC_GOLGI_APPARATUS_SUBC...,GOMF_GALACTOSYLTRANSFERASE_ACTIVITY|GOMF_GLYCO...
4,A4GALT,GOBP_CARBOHYDRATE_DERIVATIVE_BIOSYNTHETIC_PROC...,GOCC_GOLGI_APPARATUS|GOCC_GOLGI_MEMBRANE,GOMF_ACETYLGLUCOSAMINYLTRANSFERASE_ACTIVITY|GO...

In [63]:
wp_df = pd.read_csv("output/wikipathway-annotations.tsv.gz", sep="\t").rename(
    columns={
        "ncbi_geneid": "Metadata_NCBI_Gene_ID",
        "wikipathway": "Metadata_wikipathway",
    }
)

wp_df.head()

   Metadata_NCBI_Gene_ID                               Metadata_wikipathway
0                     10  WP_ARYLAMINE_METABOLISM|WP_METAPATHWAY_BIOTRAN...
1                    100  WP_CIRCADIAN_RHYTHM_GENES|WP_PURINE_METABOLISM...
2                   1000  WP_ARRHYTHMOGENIC_RIGHT_VENTRICULAR_CARDIOMYOP...
3                  10000  WP_ALZHEIMER_39_S_DISEASE|WP_ALZHEIMER_39_S_DI...
4                  10005  WP_7_OXO_C_AND_7_BETA_HC_PATHWAYS|WP_OXYSTEROL...

In [60]:
orf_df = (
    orf_df.merge(corum_df, how="left", on="Metadata_Approved_Symbol")
    .merge(class_df, how="left", on="Metadata_Approved_Symbol")
    .merge(disease_df, how="left", on="Metadata_Approved_Symbol")
    .merge(location_df, how="left", on="Metadata_Approved_Symbol")
    .merge(gene_family, how="left", on="Metadata_Approved_Symbol")
    .merge(homolog_df, how="left", on="Metadata_Approved_Symbol")
    .merge(go_df, how="left", on="Metadata_Approved_Symbol")
    .merge(wp_df, how="left", on="Metadata_NCBI_Gene_ID")
)

orf_df.count()

Metadata_JCP2022                 15162
Metadata_broad_sample            15162
Metadata_Name                    15152
Metadata_Vector                  15162
Metadata_Transcript              15126
Metadata_Symbol                  15127
Metadata_NCBI_Gene_ID            15127
Metadata_Taxon_ID                15127
Metadata_Gene_Description        14873
Metadata_Prot_Match              14340
Metadata_Insert_Length           15161
Metadata_pert_type               15162
Metadata_Approved_Symbol         14943
Metadata_complexname              3793
Metadata_protein_class           14504
Metadata_disease_involvement      4693
Metadata_subcellular_location    10381
Metadata_gene_group_id           11315
Metadata_homologue               13501
Metadata_biological_process      12797
Metadata_cellular_component      10477
Metadata_molecular_function      11825
dtype: int64

In [61]:
crispr_df = (
    crispr_df.merge(corum_df, how="left", on="Metadata_Approved_Symbol")
    .merge(class_df, how="left", on="Metadata_Approved_Symbol")
    .merge(disease_df, how="left", on="Metadata_Approved_Symbol")
    .merge(location_df, how="left", on="Metadata_Approved_Symbol")
    .merge(gene_family, how="left", on="Metadata_Approved_Symbol")
    .merge(homolog_df, how="left", on="Metadata_Approved_Symbol")
    .merge(go_df, how="left", on="Metadata_Approved_Symbol")
)

crispr_df.count()

Metadata_JCP2022                 7991
Metadata_NCBI_Gene_ID            7989
Metadata_Symbol                  7991
Metadata_Approved_Symbol         7989
Metadata_complexname             2245
Metadata_protein_class           7969
Metadata_disease_involvement     3476
Metadata_subcellular_location    5723
Metadata_gene_group_id           6864
Metadata_homologue               7717
Metadata_biological_process      7688
Metadata_cellular_component      6249
Metadata_molecular_function      7662
dtype: int64