In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels

In [2]:
variable = "expression"
col_name = f"Metadata_{variable}"
col_name_in_metadata = "Metadata_TPM"
output_df = pd.DataFrame()

In [3]:
orf_plate_metadata_df = pd.read_csv(
    "output/orf_well_plate_platemap.csv.gz",
    usecols=["Metadata_JCP2022", "Metadata_Platemap"],
)
orf_plate_metadata_df.head()

  Metadata_JCP2022 Metadata_Platemap
0   JCP2022_905588        platemap_1
1   JCP2022_912241        platemap_1
2   JCP2022_900266        platemap_1
3   JCP2022_915129        platemap_1
4   JCP2022_907177        platemap_1

In [4]:
orf_annotation_df = (
    pd.read_csv(
        "../00.download-and-process-annotations/output/orf_metadata.tsv.gz",
        sep="\t",
        usecols=["Metadata_JCP2022", col_name_in_metadata],
    )
    .assign(
        col=lambda x: np.where(
            x[col_name_in_metadata] > np.nanpercentile(x.Metadata_TPM, 75),
            "True",
            "False",
        )
    )
    .rename(columns={"col": col_name})
)

orf_df = (
    orf_plate_metadata_df.merge(orf_annotation_df, on="Metadata_JCP2022", how="left")
    .dropna(subset=[col_name])
    .drop_duplicates(subset=["Metadata_JCP2022", "Metadata_Platemap"])
)

orf_df.head()

  Metadata_JCP2022 Metadata_Platemap  Metadata_TPM Metadata_expression
0   JCP2022_905588        platemap_1      5.727104                True
1   JCP2022_912241        platemap_1      0.000000               False
2   JCP2022_900266        platemap_1      0.000000               False
3   JCP2022_915129        platemap_1           NaN               False
4   JCP2022_907177        platemap_1      4.035624               False

Fisher's exact test

In [5]:
fisher_df = pd.DataFrame(
    columns=[
        "platemap",
        f"{variable}_False_in_other_platemaps"
        f"{variable}_False_in_platemap",
        f"{variable}_True_in_other_platemaps",
        f"{variable}_True_in_platemap",
        "odds_ratio",
        "pvalue",
        "adjusted_pvalue",
    ]
)

for platemap in orf_df.Metadata_Platemap.unique():
    df = orf_df.assign(platemap_x = lambda x: np.where(x.Metadata_Platemap == platemap, True, False))
    table = sm.stats.Table.from_data(df[["platemap_x", col_name]])

    odds_ratio, pvalue = stats.fisher_exact(table.table)

    output_df = pd.concat(
        [
            output_df,
            pd.DataFrame(
                {
                    "platemap": platemap,
                    f"{variable}_False_in_other_platemaps": int(table.table[0, 0]),
                    f"{variable}_False_in_platemap": int(table.table[0, 1]),
                    f"{variable}_True_in_other_platemaps": int(table.table[1, 0]),
                    f"{variable}_True_in_platemap": int(table.table[1, 1]),
                    "odds_ratio": odds_ratio,
                    "pvalue": pvalue,
                },
                index=[0],
            ),
        ],
        ignore_index=True,
    )

output_df["adjusted_pvalue"] = statsmodels.stats.multitest.fdrcorrection(output_df.pvalue)[1]

In [6]:
print(
    output_df.sort_values(by="adjusted_pvalue")
    .query("adjusted_pvalue < 0.05")
    .to_markdown(index=False)
)

output_df.to_csv(f"output/{variable}_fisher_exact_orf.tsv", sep="\t", index=False)

| platemap    |   expression_False_in_other_platemaps |   expression_False_in_platemap |   expression_True_in_other_platemaps |   expression_True_in_platemap |   odds_ratio |      pvalue |   adjusted_pvalue |
|:------------|--------------------------------------:|-------------------------------:|-------------------------------------:|------------------------------:|-------------:|------------:|------------------:|
| platemap_43 |                                 11521 |                           3611 |                                  320 |                            25 |     0.24926  | 1.30654e-15 |       5.87942e-14 |
| platemap_30 |                                 11532 |                           3603 |                                  309 |                            33 |     0.341819 | 4.04272e-11 |       9.09612e-10 |
| platemap_39 |                                 11539 |                           3595 |                                  302 |                            41 |     0.435759 | 6.9622e-08  |       1.04433e-06 |
| platemap_25 |                                 11617 |                           3511 |                                  224 |                           125 |     1.8464   | 1.83445e-07 |       2.06376e-06 |
| platemap_34 |                                 11618 |                           3516 |                                  223 |                           120 |     1.77811  | 1.16995e-06 |       1.05296e-05 |
| platemap_10 |                                 11613 |                           3515 |                                  228 |                           121 |     1.75335  | 1.96486e-06 |       1.47364e-05 |
| platemap_13 |                                 11611 |                           3517 |                                  230 |                           119 |     1.70811  | 6.87571e-06 |       4.4201e-05  |
| platemap_42 |                                 11546 |                           3587 |                                  295 |                            49 |     0.534656 | 2.01957e-05 |       0.000113601 |
| platemap_28 |                                 11608 |                           3520 |                                  233 |                           116 |     1.64179  | 3.03132e-05 |       0.00013641  |
| platemap_22 |                                 11544 |                           3586 |                                  297 |                            50 |     0.54195  | 2.88242e-05 |       0.00013641  |
| platemap_29 |                                 11546 |                           3586 |                                  295 |                            50 |     0.545719 | 3.63879e-05 |       0.00014886  |
| platemap_17 |                                 11601 |                           3527 |                                  240 |                           109 |     1.49384  | 0.000865527 |       0.00324573  |
| platemap_15 |                                 11601 |                           3528 |                                  240 |                           108 |     1.47972  | 0.0010852   |       0.00375646  |
| platemap_21 |                                 11550 |                           3579 |                                  291 |                            57 |     0.632124 | 0.00134143  |       0.00408643  |
| platemap_12 |                                 11600 |                           3528 |                                  241 |                           108 |     1.47345  | 0.00136214  |       0.00408643  |
| platemap_40 |                                 11554 |                           3579 |                                  287 |                            57 |     0.641156 | 0.00196426  |       0.00519951  |
| platemap_2  |                                 11555 |                           3579 |                                  286 |                            57 |     0.643453 | 0.00195438  |       0.00519951  |
| platemap_1  |                                 11555 |                           3575 |                                  286 |                            61 |     0.689378 | 0.00852236  |       0.0213059   |
| platemap_41 |                                 11554 |                           3574 |                                  287 |                            62 |     0.698373 | 0.0105124   |       0.0236529   |
| platemap_38 |                                 11596 |                           3534 |                                  245 |                           102 |     1.36608  | 0.0103335   |       0.0236529   |
| platemap_33 |                                 11597 |                           3536 |                                  244 |                           100 |     1.34414  | 0.0171425   |       0.0360843   |
| platemap_3  |                                 11572 |                           3577 |                                  269 |                            59 |     0.70956  | 0.0176412   |       0.0360843   |
| platemap_23 |                                 11556 |                           3572 |                                  285 |                            64 |     0.726493 | 0.0214062   |       0.0418816   |
| platemap_20 |                                 11596 |                           3537 |                                  245 |                            99 |     1.32478  | 0.0241701   |       0.045319    |