In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels

In [2]:
variable = "long_insert_size"
col_name = f"Metadata_{variable}"
col_name_in_metadata = "Metadata_Insert_Length"
output_df = pd.DataFrame()

In [3]:
orf_plate_metadata_df = pd.read_csv(
    "output/orf_well_plate_platemap.csv.gz",
    usecols=["Metadata_JCP2022", "Metadata_Platemap"],
)
orf_plate_metadata_df.head()

  Metadata_JCP2022 Metadata_Platemap
0   JCP2022_905588        platemap_1
1   JCP2022_912241        platemap_1
2   JCP2022_900266        platemap_1
3   JCP2022_915129        platemap_1
4   JCP2022_907177        platemap_1

In [4]:
orf_annotation_df = (
    pd.read_csv(
        "../00.download-and-process-annotations/output/orf_metadata.tsv.gz",
        sep="\t",
        usecols=["Metadata_JCP2022", col_name_in_metadata],
    )
    .assign(col=lambda x: np.where(x[col_name_in_metadata] > 2500, "True", "False"))
    .rename(columns={"col": col_name})
)

orf_df = (
    orf_plate_metadata_df.merge(orf_annotation_df, on="Metadata_JCP2022", how="left")
    .dropna(subset=[col_name])
    .drop_duplicates(subset=["Metadata_JCP2022", "Metadata_Platemap"])
)

orf_df.head()

,Metadata_JCP2022,Metadata_Platemap,Metadata_Insert_Length,Metadata_long_insert_size
0,JCP2022_905588,platemap_1,1116.0,False
1,JCP2022_912241,platemap_1,336.0,False
2,JCP2022_900266,platemap_1,843.0,False
3,JCP2022_915129,platemap_1,824.0,False
4,JCP2022_907177,platemap_1,1959.0,False

Fisher's exact test

In [5]:
fisher_df = pd.DataFrame(
    columns=[
        "platemap",
        f"{variable}_False_in_other_platemaps"
        f"{variable}_False_in_platemap",
        f"{variable}_True_in_other_platemaps",
        f"{variable}_True_in_platemap",
        "odds_ratio",
        "pvalue",
        "adjusted_pvalue",
    ]
)

for platemap in orf_df.Metadata_Platemap.unique():
    df = orf_df.assign(platemap_x = lambda x: np.where(x.Metadata_Platemap == platemap, True, False))
    table = sm.stats.Table.from_data(df[["platemap_x", col_name]])

    odds_ratio, pvalue = stats.fisher_exact(table.table)

    output_df = pd.concat(
        [
            output_df,
            pd.DataFrame(
                {
                    "platemap": platemap,
                    f"{variable}_False_in_other_platemaps": int(table.table[0, 0]),
                    f"{variable}_False_in_platemap": int(table.table[0, 1]),
                    f"{variable}_True_in_other_platemaps": int(table.table[1, 0]),
                    f"{variable}_True_in_platemap": int(table.table[1, 1]),
                    "odds_ratio": odds_ratio,
                    "pvalue": pvalue,
                },
                index=[0],
            ),
        ],
        ignore_index=True,
    )

output_df["adjusted_pvalue"] = statsmodels.stats.multitest.fdrcorrection(output_df.pvalue)[1]

In [6]:
print(
    output_df.sort_values(by="adjusted_pvalue")
    .query("adjusted_pvalue < 0.05")
    .to_markdown(index=False)
)

output_df.to_csv(f"output/{variable}_fisher_exact_orf.tsv", sep="\t", index=False)

| platemap    |   long_insert_size_False_in_other_platemaps |   long_insert_size_False_in_platemap |   long_insert_size_True_in_other_platemaps |   long_insert_size_True_in_platemap |   odds_ratio |      pvalue |   adjusted_pvalue |
|:------------|--------------------------------------------:|-------------------------------------:|-------------------------------------------:|------------------------------------:|-------------:|------------:|------------------:|
| platemap_2  |                                       14506 |                                  628 |                                         36 |                                 307 |  196.981     | 0           |       0           |
| platemap_19 |                                       14267 |                                  870 |                                        275 |                                  65 |    3.87609   | 5.64647e-17 |       8.46971e-16 |
| platemap_6  |                                       14336 |                                  879 |                                        206 |                                  56 |    4.43363   | 4.96103e-17 |       8.46971e-16 |
| platemap_26 |                                       14255 |                                  877 |                                        287 |                                  58 |    3.28484   | 9.2474e-13  |       1.04033e-11 |
| platemap_22 |                                       14196 |                                  934 |                                        346 |                                   1 |    0.0439282 | 1.60096e-08 |       4.61958e-08 |
| platemap_39 |                                       14200 |                                  934 |                                        342 |                                   1 |    0.0444545 | 1.534e-08   |       4.61958e-08 |
| platemap_17 |                                       14194 |                                  934 |                                        348 |                                   1 |    0.0436695 | 1.0364e-08  |       4.61958e-08 |
| platemap_36 |                                       14199 |                                  934 |                                        343 |                                   1 |    0.0443217 | 1.53664e-08 |       4.61958e-08 |
| platemap_12 |                                       14194 |                                  934 |                                        348 |                                   1 |    0.0436695 | 1.0364e-08  |       4.61958e-08 |
| platemap_40 |                                       14199 |                                  934 |                                        343 |                                   1 |    0.0443217 | 1.53664e-08 |       4.61958e-08 |
| platemap_31 |                                       14194 |                                  934 |                                        348 |                                   1 |    0.0436695 | 1.0364e-08  |       4.61958e-08 |
| platemap_9  |                                       14195 |                                  934 |                                        347 |                                   1 |    0.0437985 | 1.64252e-08 |       4.61958e-08 |
| platemap_42 |                                       14199 |                                  934 |                                        343 |                                   1 |    0.0443217 | 1.53664e-08 |       4.61958e-08 |
| platemap_32 |                                       14197 |                                  934 |                                        345 |                                   1 |    0.0440586 | 1.56975e-08 |       4.61958e-08 |
| platemap_43 |                                       14198 |                                  934 |                                        344 |                                   1 |    0.0441898 | 1.54844e-08 |       4.61958e-08 |
| platemap_10 |                                       14194 |                                  934 |                                        348 |                                   1 |    0.0436695 | 1.0364e-08  |       4.61958e-08 |
| platemap_30 |                                       14201 |                                  934 |                                        341 |                                   1 |    0.044588  | 2.46445e-08 |       6.52355e-08 |
| platemap_20 |                                       14246 |                                  887 |                                        296 |                                  48 |    2.60447   | 5.6143e-08  |       1.40358e-07 |
| platemap_27 |                                       14244 |                                  887 |                                        298 |                                  48 |    2.58662   | 6.45274e-08 |       1.52828e-07 |
| platemap_8  |                                       14197 |                                  933 |                                        345 |                                   2 |    0.0882116 | 1.51523e-07 |       3.14695e-07 |
| platemap_15 |                                       14196 |                                  933 |                                        346 |                                   2 |    0.0879505 | 1.52287e-07 |       3.14695e-07 |
| platemap_13 |                                       14195 |                                  933 |                                        347 |                                   2 |    0.0876908 | 1.53851e-07 |       3.14695e-07 |
| platemap_34 |                                       14201 |                                  933 |                                        341 |                                   2 |    0.0892715 | 2.26532e-07 |       4.43215e-07 |
| platemap_14 |                                       14196 |                                  932 |                                        346 |                                   3 |    0.132067  | 1.11948e-06 |       2.09902e-06 |
| platemap_4  |                                       14238 |                                  890 |                                        304 |                                  45 |    2.36809   | 1.82658e-06 |       3.28784e-06 |
| platemap_16 |                                       14249 |                                  893 |                                        293 |                                  42 |    2.28726   | 6.89364e-06 |       1.14894e-05 |
| platemap_25 |                                       14197 |                                  931 |                                        345 |                                   4 |    0.176802  | 6.65088e-06 |       1.14894e-05 |
| platemap_5  |                                       14200 |                                  930 |                                        342 |                                   5 |    0.223228  | 3.32034e-05 |       5.33627e-05 |
| platemap_23 |                                       14199 |                                  929 |                                        343 |                                   6 |    0.267362  | 0.00014464  |       0.000224442 |
| platemap_37 |                                       14200 |                                  928 |                                        342 |                                   7 |    0.313193  | 0.000556469 |       0.000834703 |
| platemap_38 |                                       14204 |                                  926 |                                        338 |                                   9 |    0.408437  | 0.00410299  |       0.00562532  |
| platemap_45 |                                       14205 |                                  926 |                                        337 |                                   9 |    0.409678  | 0.00408779  |       0.00562532  |
| platemap_21 |                                       14203 |                                  926 |                                        339 |                                   9 |    0.407204  | 0.00412523  |       0.00562532  |
| platemap_41 |                                       14203 |                                  925 |                                        339 |                                  10 |    0.452938  | 0.00862173  |       0.0114111   |